<a href="https://colab.research.google.com/github/fortune-max/M4-python-refresher-ml/blob/main/Day5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Working with numpy
https://education.yandex.ru/handbook/python/article/moduli-math-i-numpy

### Array Creation:

- np.array(): Create an array.
- np.zeros(), np.ones(), np.empty(): Create arrays filled with zeros, ones, or uninitialized values.
- np.arange(), np.linspace(): Create arrays with regularly spaced values.
Array Operations:

### Mathematical operations:
- +, -, *, /, ** for element-wise addition, subtraction, multiplication, division, and exponentiation.
- np.dot(), np.matmul(): Matrix multiplication.
- np.sum(), np.mean(), np.median(), np.std(): Basic statistical operations.
- np.min(), np.max(): Minimum and maximum values in an array.
- np.unique(): Find unique elements in an array.

### Array Manipulation:
- np.reshape(): Reshape an array.
- np.concatenate(), np.vstack(), np.hstack(): Join arrays.
- np.split(): Split an array into multiple sub-arrays.
- np.transpose(), array.T: Transpose an array.

### Indexing and Slicing:
Indexing and slicing for accessing elements or subarrays.
Boolean indexing: Select elements based on conditions.

### Random:
- np.random.rand(), np.random.randn(): Generate random numbers.
- np.random.randint(): Generate random integers.
- np.random.shuffle(), np.random.choice(): Shuffle and make random selections.

### Linear Algebra:
- np.linalg.inv(): Compute the inverse of a matrix.
- np.linalg.det(): Compute the determinant of a matrix.
- np.linalg.eig(): Compute the eigenvalues and eigenvectors of a matrix.
- np.linalg.solve(): Solve a system of linear equations.

### Statistical Functions:
- np.percentile(): Calculate the q-th percentile of the data.
- np.corrcoef(): Compute the correlation matrix.
- np.cov(): Compute the covariance matrix.

### Trigonometric and Other Functions:
- np.sin(), np.cos(), np.tan(): Trigonometric functions.
- np.exp(), np.log(), np.sqrt(): Exponential, logarithmic, and square root functions.

### Aggregation Functions:
- np.sum(), np.prod(): Compute the sum and product of array elements.
- np.cumsum(), np.cumprod(): Compute the cumulative sum and product.


## Exersices

In [1]:
import numpy as np

In [2]:
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d)


[1 2 3 4 5]


In [3]:
a = np.zeros((4, 3), dtype="uint8")
print(a)
print()
a = a.reshape((2, 2, -1))
a

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]



array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [7]:
# Creating a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d.shape)
a = arr_2d.reshape((2, 1, -1))
a

(2, 3)


array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [6]:
a = np.array([9, 8, 7])
b = np.array([1, 2, 3])
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[10 10 10]
[8 6 4]
[ 9 16 21]
[9.         4.         2.33333333]


In [ ]:
# Array shape
shape = arr_2d.shape

# Array dimensions
dimensions = arr_2d.ndim

# Array data type
dtype = arr_2d.dtype

# Array size
size = arr_2d.size

# Array reshape
reshaped_arr = arr_1d.reshape(5, 1)

# Slicing a 1D array
sliced_arr_1d = arr_1d[1:4]

# Slicing a 2D array
sliced_arr_2d = arr_2d[0:2, 1:3]

# Array indexing
element = arr_2d[1, 2]

# Array operations (addition)
arr_add = arr_1d + 5

# Array operations (multiplication)
arr_mult = arr_1d * 2

# Element-wise operations
arr_squared = np.square(arr_1d)

# Array concatenation
arr_concat = np.concatenate((arr_1d, arr_add))

# Array stacking
arr_stack = np.vstack((arr_1d, arr_add))

#  Array transposition
arr_transposed = arr_2d.T

#  Random number generation
rand_arr = np.random.rand(3, 3)

#  Finding unique elements and counts
unique_elements, counts = np.unique(arr_1d, return_counts=True)

# Reshaping and flattening
reshaped_flattened = arr_2d.reshape(-1)

#  Matrix multiplication
matrix_mult = np.dot(arr_2d, arr_transposed)

# Element-wise comparison
arr_comparison = (arr_1d > 3)

# Extracting elements based on a condition
arr_condition = arr_1d[arr_1d > 2]

# Sorting an array
sorted_arr = np.sort(arr_1d)

# Finding maximum and minimum
max_val = np.max(arr_1d)
min_val = np.min(arr_1d)

# Calculating mean and standard deviation
mean_val = np.mean(arr_1d)
std_dev = np.std(arr_1d)

# Creating an identity matrix
identity_matrix = np.eye(3)

# Solving a system of linear equations
coefficients = np.array([[2, 1], [1, 1]])
constants = np.array([8, 5])
solution = np.linalg.solve(coefficients, constants)


## Exercises:


### 1D Arrays:
Create a NumPy array with values from 1 to 10.



In [8]:
vct = np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

Calculate the square of each element in the array.


In [13]:
vct = np.linspace(1, 10, 10)
np.power(vct, 2)

array([  1.,   4.,   9.,  16.,  25.,  36.,  49.,  64.,  81., 100.])

Find the sum, mean, and standard deviation of the array.


In [18]:
print(f"mean = {np.mean(vct)}")
print(f"sum = {np.sum(vct)}")
print(f"std = {np.std(vct)}")

mean = 5.5
sum = 55.0
std = 2.8722813232690143



### 2D Arrays:
Create a 3x3 matrix with random values between 0 and 1.


In [29]:
arr_2d = np.random.rand(3, 3)
print(arr_2d)

[[0.61209572 0.616934   0.94374808]
 [0.6818203  0.3595079  0.43703195]
 [0.6976312  0.06022547 0.66676672]]


Reshape the matrix from exercise 4 into a 1D array.


In [39]:
print(arr_2d)
print('rows only', arr_2d.reshape((9, 1)))
print(np.array_equal(arr_2d.reshape((-1, 1)), arr_2d.reshape((9, 1))))
print('cols only', arr_2d.reshape((1, 9)))
print(np.array_equal(arr_2d.reshape((1, -1)), arr_2d.reshape((1, 9))))


[[0.61209572 0.616934   0.94374808]
 [0.6818203  0.3595079  0.43703195]
 [0.6976312  0.06022547 0.66676672]]
rows only [[0.61209572]
 [0.616934  ]
 [0.94374808]
 [0.6818203 ]
 [0.3595079 ]
 [0.43703195]
 [0.6976312 ]
 [0.06022547]
 [0.66676672]]
True
cols only [[0.61209572 0.616934   0.94374808 0.6818203  0.3595079  0.43703195
  0.6976312  0.06022547 0.66676672]]
True


Calculate the row-wise and column-wise sums of the matrix.


In [44]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
col_sum = np.sum(arr, axis=0)
row_sum = np.sum(arr, axis=1)
print('Column sum:', col_sum)
print('Row sum:', row_sum)

# OR
print()
print('Column sum:', arr.sum(axis=0))
print('Row sum:', arr.sum(axis=1))

Column sum: [12 15 18]
Row sum: [ 6 15 24]

Column sum: [12 15 18]
Row sum: [ 6 15 24]



#### Advanced 2D Operations:
Create a 3x3 matrix with values 1, 2, 3 on the diagonal and zeros elsewhere.


In [48]:
diag = np.eye(3) * [1, 2, 3]
print(diag)
diag_2 = np.diag([1, 2, 3])
print(diag_2)

[[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 3.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


Replace all zeros in the matrix from exercise 7 with the corresponding row number.


In [72]:
diag_2_upd = diag_2.copy()
for (row, col), val in np.ndenumerate(diag_2_upd):
    if val == 0:
        diag_2_upd[row][col] = row + 1
print(diag_2_upd)

# OR

# np.arange(0, 3).reshape((3, 1)) + np.arange(1, 4).reshape((1, 3))
diag_2_upd_2 = np.arange(0, 3).reshape(3, 1) * np.ones(3).reshape(1, 3)
print(diag_2_upd_2)

# OR

diag_2_upd_3 = diag_2.copy()
zero_rows, zero_cols = np.where(diag_2_upd_3 == 0)
diag_2_upd_3[zero_rows, zero_cols] = zero_rows + 1
print(diag_2_upd_3)

[[1 1 1]
 [2 2 2]
 [3 3 3]]
[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]]
[[1 1 1]
 [2 2 2]
 [3 3 3]]


### 3D Arrays:


Create a 3x3x3 array with random integers between 1 and 100.


In [68]:
# create a 3x3x3 array with random values between 1 and 10
arr_3d = np.random.randint(1, 10, (3, 3, 3))
print(arr_3d)

[[[3 8 6]
  [3 1 3]
  [5 3 1]]

 [[5 7 7]
  [9 3 7]
  [1 4 4]]

 [[5 7 7]
  [4 7 3]
  [6 2 9]]]


Sum along the third axis of the array from exercise 9.


In [69]:
sum_of_axis_3 = np.sum(arr_3d, axis=2)
print(sum_of_axis_3)

[[17  7  9]
 [19 19  9]
 [19 14 17]]



### Slicing and Indexing:


Create a 1D array with values from 0 to 9.


In [73]:
arr_1d = np.linspace(1, 9, 9)
print(arr_1d)

[1. 2. 3. 4. 5. 6. 7. 8. 9.]


Select all odd-indexed elements from the array from exercise 11.


In [79]:
# print all odd-indexed elements
print(arr_1d[::2])
# OR
print(arr_1d[arr_1d % 2 == 1])
# OR
print(arr_1d[np.arange(0, 9, 2)])
# OR
print(arr_1d[np.where(arr_1d % 2)])

[1. 3. 5. 7. 9.]
[1. 3. 5. 7. 9.]
[1. 3. 5. 7. 9.]


### Confusing Methods:


Create a 2D array with values from 1 to 9 and transpose it.


In [84]:
arr_2d = np.arange(9).reshape(3, 3)
print(arr_2d)
arr_2d_transpose = arr_2d.T
print(arr_2d_transpose)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]


Use np.concatenate() to join two 1D arrays.


In [86]:
arr_cat = np.concatenate((arr_2d, arr_2d_transpose), axis=1)
print(arr_cat)

[[0 1 2 0 3 6]
 [3 4 5 1 4 7]
 [6 7 8 2 5 8]]


### Advanced Indexing:


Create a 2D array and set all elements in the first row to zero.


In [90]:
arr_2d_to_set = np.arange(9).reshape([3, 3]) # or reshape(3, 3)
print(arr_2d_to_set)
arr_2d_to_set[[0]] = 0
print(arr_2d_to_set)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 0 0]
 [3 4 5]
 [6 7 8]]


Use boolean indexing to replace all negative values in a random array with zero.


In [105]:
matrix_w_negs = np.random.randint(-10, 10, (3, 3))
print(matrix_w_negs)
matrix_w_negs[matrix_w_negs < 0] = 0
print(matrix_w_negs)

[[ -1  -8  -4]
 [  5   5   9]
 [  6  -9 -10]]
[[0 0 0]
 [5 5 9]
 [6 0 0]]


### Statistical Operations:


Create a random 1D array and find the index of its maximum value.
Compute the correlation matrix for a 3x3 matrix of random values.


In [99]:
my_arr = np.random.randint(1, 10, 6)
print(my_arr)
max_idx = np.argmax(my_arr)
print(max_idx)

[1 1 4 7 2 3]
3


In [104]:
matrix = np.random.randint(1, 10, (3, 3))
print(matrix)
corr_matrix = np.corrcoef(matrix, rowvar=False)
print(corr_matrix)

[[8 7 2]
 [8 1 9]
 [9 2 7]]
[[ 1.         -0.3592106   0.24019223]
 [-0.3592106   1.         -0.99221536]
 [ 0.24019223 -0.99221536  1.        ]]


*

1. Write a NumPy program to find the dot product of two arrays of different dimensions.



2. Write a NumPy program to create a 3x3 identity matrix and stack it vertically and horizontally.


In [108]:
my_mat = np.eye(3)
print(np.concatenate((my_mat, my_mat), axis=0))
print(np.concatenate((my_mat, my_mat), axis=1))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 1.]]



3. Write a NumPy program to create a 4x4 array with random values and find the sum of each row.


4. Write a NumPy program to create a 3x3 array with random values and subtract the mean of each row from each element.



5. Write a NumPy program to create a 3x3 array with random values and subtract the mean of each column from each element.


6. Write a NumPy program to create a 5x5 array with random values and normalize it row-wise.



7. Write a NumPy program to create a 5x5 array with random values and normalize it column-wise.


8. Write a NumPy program to create a 3x3x3 array with random values and find the sum along the last axis.



9. Write a NumPy program to create a 5x5 array with random values and sort each row.



10. Write a NumPy program to create a 5x5 array with random values and sort each column.


11. Write a NumPy program to create a 5x5 array with random values and find the second-largest value in each row.



12. Write a NumPy program to create a 5x5 array with random values and find the second-largest value in each column.



13. Write a NumPy program to create a 5x5 array with random values and replace the maximum value with 0.



14. Write a NumPy program to create a 5x5 array with random values and replace the minimum value with 0.




15. Write a NumPy program to create a 5x5 array with random values and calculate the exponential of each element.




## Additional info
https://www.simplilearn.com/keras-vs-tensorflow-vs-pytorch-article