<a href="https://colab.research.google.com/github/fortune-max/M4-python-refresher-ml/blob/main/Day5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Working with numpy
https://education.yandex.ru/handbook/python/article/moduli-math-i-numpy

### Array Creation:

- np.array(): Create an array.
- np.zeros(), np.ones(), np.empty(): Create arrays filled with zeros, ones, or uninitialized values.
- np.arange(), np.linspace(): Create arrays with regularly spaced values.
Array Operations:

### Mathematical operations:
- +, -, *, /, ** for element-wise addition, subtraction, multiplication, division, and exponentiation.
- np.dot(), np.matmul(): Matrix multiplication.
- np.sum(), np.mean(), np.median(), np.std(): Basic statistical operations.
- np.min(), np.max(): Minimum and maximum values in an array.
- np.unique(): Find unique elements in an array.

### Array Manipulation:
- np.reshape(): Reshape an array.
- np.concatenate(), np.vstack(), np.hstack(): Join arrays.
- np.split(): Split an array into multiple sub-arrays.
- np.transpose(), array.T: Transpose an array.

### Indexing and Slicing:
Indexing and slicing for accessing elements or subarrays.
Boolean indexing: Select elements based on conditions.

### Random:
- np.random.rand(), np.random.randn(): Generate random numbers.
- np.random.randint(): Generate random integers.
- np.random.shuffle(), np.random.choice(): Shuffle and make random selections.

### Linear Algebra:
- np.linalg.inv(): Compute the inverse of a matrix.
- np.linalg.det(): Compute the determinant of a matrix.
- np.linalg.eig(): Compute the eigenvalues and eigenvectors of a matrix.
- np.linalg.solve(): Solve a system of linear equations.

### Statistical Functions:
- np.percentile(): Calculate the q-th percentile of the data.
- np.corrcoef(): Compute the correlation matrix.
- np.cov(): Compute the covariance matrix.

### Trigonometric and Other Functions:
- np.sin(), np.cos(), np.tan(): Trigonometric functions.
- np.exp(), np.log(), np.sqrt(): Exponential, logarithmic, and square root functions.

### Aggregation Functions:
- np.sum(), np.prod(): Compute the sum and product of array elements.
- np.cumsum(), np.cumprod(): Compute the cumulative sum and product.


## Exersices

In [ ]:
import numpy as np

In [ ]:
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d)


[1 2 3 4 5]


In [ ]:
import numpy as np

a = np.zeros((4, 3), dtype="uint8")
print(a)
print()
a = a.reshape((-1, -1, -1))
a

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]



ValueError: ignored

In [ ]:
# Creating a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d.shape)
a = arr_2d.reshape((2, 1, -1))
a


import numpy as np

a = np.array([9, 8, 7])
b = np.array([1, 2, 3])
print(a + b)
print(a - b)
print(a * b)
print(a / b)

(2, 3)


array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [ ]:
import numpy as np

a = np.array([9, 8, 7])
b = np.array([1, 2, 3])
print(a + b)
print(a - b)
print(a * b)
print(a / b)

ValueError: ignored

In [ ]:
# Array shape
shape = arr_2d.shape

# Array dimensions
dimensions = arr_2d.ndim

# Array data type
dtype = arr_2d.dtype

# Array size
size = arr_2d.size

# Array reshape
reshaped_arr = arr_1d.reshape(5, 1)

# Slicing a 1D array
sliced_arr_1d = arr_1d[1:4]

# Slicing a 2D array
sliced_arr_2d = arr_2d[0:2, 1:3]

# Array indexing
element = arr_2d[1, 2]

# Array operations (addition)
arr_add = arr_1d + 5

# Array operations (multiplication)
arr_mult = arr_1d * 2

# Element-wise operations
arr_squared = np.square(arr_1d)

# Array concatenation
arr_concat = np.concatenate((arr_1d, arr_add))

# Array stacking
arr_stack = np.vstack((arr_1d, arr_add))

#  Array transposition
arr_transposed = arr_2d.T

#  Random number generation
rand_arr = np.random.rand(3, 3)

#  Finding unique elements and counts
unique_elements, counts = np.unique(arr_1d, return_counts=True)

# Reshaping and flattening
reshaped_flattened = arr_2d.reshape(-1)

#  Matrix multiplication
matrix_mult = np.dot(arr_2d, arr_transposed)

# Element-wise comparison
arr_comparison = (arr_1d > 3)

# Extracting elements based on a condition
arr_condition = arr_1d[arr_1d > 2]

# Sorting an array
sorted_arr = np.sort(arr_1d)

# Finding maximum and minimum
max_val = np.max(arr_1d)
min_val = np.min(arr_1d)

# Calculating mean and standard deviation
mean_val = np.mean(arr_1d)
std_dev = np.std(arr_1d)

# Creating an identity matrix
identity_matrix = np.eye(3)

# Solving a system of linear equations
coefficients = np.array([[2, 1], [1, 1]])
constants = np.array([8, 5])
solution = np.linalg.solve(coefficients, constants)


## Exercises:


### 1D Arrays:
Create a NumPy array with values from 1 to 10.



Calculate the square of each element in the array.


Find the sum, mean, and standard deviation of the array.



### 2D Arrays:
Create a 3x3 matrix with random values between 0 and 1.


Reshape the matrix from exercise 4 into a 1D array.


Calculate the row-wise and column-wise sums of the matrix.



#### Advanced 2D Operations:
Create a 3x3 matrix with values 1, 2, 3 on the diagonal and zeros elsewhere.


Replace all zeros in the matrix from exercise 7 with the corresponding row number.


### 3D Arrays:


Create a 3x3x3 array with random integers between 1 and 100.


Sum along the third axis of the array from exercise 9.



### Slicing and Indexing:


Create a 1D array with values from 0 to 9.


Select all odd-indexed elements from the array from exercise 11.


### Confusing Methods:


Create a 2D array with values from 1 to 9 and transpose it.


Use np.concatenate() to join two 1D arrays.


### Advanced Indexing:


Create a 2D array and set all elements in the first row to zero.


Use boolean indexing to replace all negative values in a random array with zero.


### Statistical Operations:


Create a random 1D array and find the index of its maximum value.
Compute the correlation matrix for a 3x3 matrix of random values.


*

1. Write a NumPy program to find the dot product of two arrays of different dimensions.



2. Write a NumPy program to create a 3x3 identity matrix and stack it vertically and horizontally.



3. Write a NumPy program to create a 4x4 array with random values and find the sum of each row.


4. Write a NumPy program to create a 3x3 array with random values and subtract the mean of each row from each element.



5. Write a NumPy program to create a 3x3 array with random values and subtract the mean of each column from each element.


6. Write a NumPy program to create a 5x5 array with random values and normalize it row-wise.



7. Write a NumPy program to create a 5x5 array with random values and normalize it column-wise.


8. Write a NumPy program to create a 3x3x3 array with random values and find the sum along the last axis.



9. Write a NumPy program to create a 5x5 array with random values and sort each row.



10. Write a NumPy program to create a 5x5 array with random values and sort each column.


11. Write a NumPy program to create a 5x5 array with random values and find the second-largest value in each row.



12. Write a NumPy program to create a 5x5 array with random values and find the second-largest value in each column.



13. Write a NumPy program to create a 5x5 array with random values and replace the maximum value with 0.



14. Write a NumPy program to create a 5x5 array with random values and replace the minimum value with 0.




15. Write a NumPy program to create a 5x5 array with random values and calculate the exponential of each element.




## Additional info
https://www.simplilearn.com/keras-vs-tensorflow-vs-pytorch-article